// Copyright (c) You-Ri, 2026
using System;
using NUnit.Framework;
using UnityEngine;
using Unity.Collections.LowLevel.Unsafe;
using Lilium.RemoteControl.Frames;

namespace Lilium.RemoteControl.Tests
{
    /// <summary>
    /// A type carrying text in the state lane, declared the plain way: the field is the member.
    ///
    /// Top level rather than nested inside the fixture, because the block is emitted inside the
    /// owner and a nested owner is refused (LRC003).
    /// </summary>
    [LiveClass("FixedTextProbe")]
    public partial class FixedTextProbe
    {
        [LiveField(lane = FrameLane.State, textCapacity = 32)]
        private string _title = string.Empty;

        [LiveField(lane = FrameLane.State)]
        private float _weight;

        public string title { get => _title; set => _title = value; }

        public float weight { get => _weight; set => _weight = value; }
    }

    /// <summary>
    /// The same, in the shape most of the exposed surface actually has: a hidden field declaring
    /// the lane and a property giving the value its behaviour. The block travels through the
    /// property, so this is where the apply side's setter is observable.
    /// </summary>
    [LiveClass("FixedTextShadowProbe")]
    public partial class FixedTextShadowProbe
    {
        [SerializeField, LiveField(lane = FrameLane.State, textCapacity = 64), Hide]
        [FormerlyNamedAs("selection")]
        private string _selection = string.Empty;

        [LiveProperty]
        public string selection
        {
            get => _selection;
            set
            {
                _selection = value;
                setterCallCount++;
            }
        }

        [SerializeField, LiveField(lane = FrameLane.State), Hide]
        [FormerlyNamedAs("weight")]
        private float _weight;

        /// <summary>Not text: the guard on this one is the generated byte comparison.</summary>
        [LiveProperty]
        public float weight
        {
            get => _weight;
            set
            {
                _weight = value;
                weightSetterCallCount++;
            }
        }

        [NonSerialized]
        public int setterCallCount;

        [NonSerialized]
        public int weightSetterCallCount;
    }

    /// <summary>
    /// Text in the state lane.
    ///
    /// There is deliberately no fixture for the two declarations the generator refuses -- a state
    /// string with no <c>textCapacity</c> (LRC005) and one asking for more than the widest block
    /// text (LRC006). Both are warnings raised while compiling the assembly that holds them, so a
    /// fixture would put a permanent warning in the package's console for everyone. What they do is
    /// leave the member where it was, which is the same outcome the event lane has always had.
    /// </summary>
    public class LiveFixedStringStateTests
    {
        [SetUp]
        public void ResetCounts() => LiveFixedStringStats.Reset();

        [TearDown]
        public void ReleaseCounts() => LiveFixedStringStats.Reset();

        [Test]
        public void TheBlock_HoldsTextAsAFixedWidth()
        {
            var field = typeof(FixedTextProbe.LiveStateBlock).GetField("_title");

            Assert.IsNotNull(field, "the declared text member did not reach the block");
            Assert.AreEqual(typeof(LiveFixedString32), field.FieldType);
        }

        [Test]
        public void AWidthCostsItsBytesPlusItsLength()
        {
            // What a member on this lane costs every frame, which is the number the declaration is
            // choosing between. The length is two bytes because two of its values are markers.
            Assert.AreEqual(32 + 2, UnsafeUtility.SizeOf<LiveFixedString32>());
            Assert.AreEqual(64 + 2, UnsafeUtility.SizeOf<LiveFixedString64>());
            Assert.AreEqual(128 + 2, UnsafeUtility.SizeOf<LiveFixedString128>());
            Assert.AreEqual(256 + 2, UnsafeUtility.SizeOf<LiveFixedString256>());
        }

        [Test]
        public void TheBlockIsStillUnmanaged_SoAFrameCanCarryItVerbatim()
        {
            Assert.DoesNotThrow(() => _RequireUnmanaged<FixedTextProbe.LiveStateBlock>());
        }

        private static void _RequireUnmanaged<T>() where T : unmanaged { }

        [Test]
        public void CaptureThenApply_CarriesTheTextAcross()
        {
            var captured = new FixedTextProbe { title = "front camera", weight = 0.5f };
            var restored = new FixedTextProbe();
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            Assert.IsTrue(bridge.Apply(restored, ownerId: 1, state));

            Assert.AreEqual("front camera", restored.title);
            Assert.AreEqual(0.5f, restored.weight);
        }

        [Test]
        public void AWidthCountsUtf8Bytes_NotCharacters()
        {
            // Ten kanji are thirty bytes and fit; eleven are thirty-three and do not. The width is
            // a claim about bytes, and a declaration that counted characters would be wrong by
            // three times over exactly the text this product is written for.
            var fits = new string('あ', 10);
            var probe = new FixedTextProbe { title = fits };
            var restored = new FixedTextProbe();
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(probe, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(fits, restored.title);
            Assert.AreEqual(0, LiveFixedStringStats.unrepresentableCount);
        }

        [Test]
        public void TextTooLongForItsWidth_IsNotCarried_AndLeavesTheTargetAlone()
        {
            var probe = new FixedTextProbe { title = new string('あ', 11) };
            var restored = new FixedTextProbe { title = "untouched" };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(probe, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);

            // Not shortened and not blanked: a value nobody set would be written back on replay and
            // then agree with itself under comparison, which is worse than a value that is missing.
            Assert.AreEqual("untouched", restored.title);
            Assert.AreEqual(1, LiveFixedStringStats.unrepresentableCount);
        }

        [Test]
        public void ANullStringIsNotAnEmptyOne()
        {
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(new FixedTextProbe { title = null }, ownerId: 1, state, default, time: 0);

            var restored = new FixedTextProbe { title = "something" };
            bridge.Apply(restored, ownerId: 1, state);
            Assert.IsNull(restored.title);

            bridge.Capture(new FixedTextProbe { title = string.Empty }, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);
            Assert.AreEqual(string.Empty, restored.title);
        }

        [Test]
        public void ApplyingTextThatHasNotChanged_DoesNotRunTheSetter()
        {
            // The state lane writes every member every frame. Without this, a replay runs the
            // setter sixty times a second for a value that has not moved -- and the setter behind
            // an asset reference answers that by loading.
            var captured = new FixedTextShadowProbe { selection = "avatar-a" };
            var restored = new FixedTextShadowProbe { selection = "avatar-a" };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextShadowProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            restored.setterCallCount = 0;
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(0, restored.setterCallCount);
            Assert.AreEqual("avatar-a", restored.selection);
        }

        [Test]
        public void ApplyingTextThatChanged_RunsTheSetterOnce()
        {
            var captured = new FixedTextShadowProbe { selection = "avatar-b" };
            var restored = new FixedTextShadowProbe { selection = "avatar-a" };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextShadowProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            restored.setterCallCount = 0;
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(1, restored.setterCallCount, "the second apply had nothing left to change");
            Assert.AreEqual("avatar-b", restored.selection);
        }

        [Test]
        public void ApplyingAnOrdinaryValueThatHasNotChanged_DoesNotRunItsSetter()
        {
            // Not text, so the guard is the generated byte comparison rather than the fixed
            // string's own. A setter is entitled to do anything; the state lane says the value
            // every frame whether or not it moved.
            var captured = new FixedTextShadowProbe { weight = 2f };
            var restored = new FixedTextShadowProbe { weight = 2f };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextShadowProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            restored.weightSetterCallCount = 0;
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(0, restored.weightSetterCallCount);
            Assert.AreEqual(2f, restored.weight);
        }

        [Test]
        public void ApplyingAnOrdinaryValueThatMoved_RunsItsSetterOnce()
        {
            var captured = new FixedTextShadowProbe { weight = 5f };
            var restored = new FixedTextShadowProbe { weight = 2f };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextShadowProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            restored.weightSetterCallCount = 0;
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(1, restored.weightSetterCallCount, "the second apply had nothing left to change");
            Assert.AreEqual(5f, restored.weight);
        }

        [Test]
        public void APlainFieldIsAssignedOutright()
        {
            // No guard on a field: writing one costs a store either way, so comparing first would
            // only add work. FixedTextProbe._weight is the field case.
            var captured = new FixedTextProbe { weight = 3f };
            var restored = new FixedTextProbe();
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(3f, restored.weight);
        }

        [Test]
        public void ABridgeSaysWhichMembersItActuallyCarries()
        {
            // Declaring the state lane and being carried by it are two different things, and only
            // the bridge knows which. See LiveEventRestateTests for what depends on the answer.
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            Assert.IsTrue(bridge.Carries("_title"));
            Assert.IsTrue(bridge.Carries("_weight"));
            Assert.IsFalse(bridge.Carries("somethingElse"));
        }

        [Test]
        public void AShadowedTextMemberTravelsThroughItsProperty()
        {
            // The field declares the lane, the property carries the value. The block names the
            // property, so a getter that reads something else entirely still reports the truth.
            var field = typeof(FixedTextShadowProbe.LiveStateBlock).GetField("selection");

            Assert.IsNotNull(field, "the block named the field instead of the property it stands behind");
            Assert.AreEqual(typeof(LiveFixedString64), field.FieldType);
        }
    }
}
