// Copyright (c) You-Ri, 2026
using System;
using NUnit.Framework;
using UnityEngine;
using Unity.Collections.LowLevel.Unsafe;
using Lilium.RemoteControl.Frames;

namespace Lilium.RemoteControl.Tests
{
    /// <summary>
    /// A type carrying text in the state lane, declared the plain way: the field is the member.
    ///
    /// Top level rather than nested inside the fixture, because the block is emitted inside the
    /// owner and a nested owner is refused (LRC003).
    /// </summary>
    [LiveClass("FixedTextProbe")]
    public partial class FixedTextProbe
    {
        [LiveField(lane = FrameLane.State, textCapacity = 32)]
        private string _title = string.Empty;

        [LiveField(lane = FrameLane.State)]
        private float _weight;

        public string title { get => _title; set => _title = value; }

        public float weight { get => _weight; set => _weight = value; }
    }

    /// <summary>
    /// The same, in the shape most of the exposed surface actually has: a hidden field declaring
    /// the lane and a property giving the value its behaviour. The block travels through the
    /// property, so this is where the apply side's setter is observable.
    /// </summary>
    [LiveClass("FixedTextShadowProbe")]
    public partial class FixedTextShadowProbe
    {
        [SerializeField, LiveField(lane = FrameLane.State, textCapacity = 64), Hide]
        [FormerlyNamedAs("selection")]
        private string _selection = string.Empty;

        [LiveProperty]
        public string selection
        {
            get => _selection;
            set
            {
                _selection = value;
                setterCallCount++;
            }
        }

        [SerializeField, LiveField(lane = FrameLane.State), Hide]
        [FormerlyNamedAs("weight")]
        private float _weight;

        /// <summary>Not text: the guard on this one is the generated byte comparison.</summary>
        [LiveProperty]
        public float weight
        {
            get => _weight;
            set
            {
                _weight = value;
                weightSetterCallCount++;
            }
        }

        [NonSerialized]
        public int setterCallCount;

        [NonSerialized]
        public int weightSetterCallCount;
    }

    /// <summary>
    /// A type whose state-lane values mean "do this", with the doing attached by declaration.
    ///
    /// The state lane carries values rather than the calls that produced them, which is what lets
    /// any frame stand on its own -- but a plain field has no setter in which to turn a value into
    /// an effect. Naming a method is how the effect gets attached, and it runs on the frame the
    /// value moved, not on every frame after.
    /// </summary>
    [LiveClass("ReactiveStateProbe")]
    public partial class ReactiveStateProbe
    {
        [LiveField(lane = FrameLane.State, onApplied = nameof(_OnModeApplied))]
        private int _mode;

        [LiveField(lane = FrameLane.State, textCapacity = 32, onApplied = nameof(_OnAssetApplied))]
        private string _asset = string.Empty;

        [LiveField(lane = FrameLane.State)]
        private float _quiet;

        public int mode { get => _mode; set => _mode = value; }

        public string asset { get => _asset; set => _asset = value; }

        public float quiet { get => _quiet; set => _quiet = value; }

        [NonSerialized] public int modeReactions;

        [NonSerialized] public int assetReactions;

        [NonSerialized] public string loaded;

        private void _OnModeApplied() => modeReactions++;

        private void _OnAssetApplied()
        {
            assetReactions++;

            // What a reaction is for: the value is the intent, and this is the effect.
            loaded = _asset;
        }
    }

    /// <summary>
    /// Text in the state lane.
    ///
    /// There is deliberately no fixture for the two declarations the generator refuses -- a state
    /// string with no <c>textCapacity</c> (LRC005) and one asking for more than the widest block
    /// text (LRC006). Both are warnings raised while compiling the assembly that holds them, so a
    /// fixture would put a permanent warning in the package's console for everyone. What they do is
    /// leave the member where it was, which is the same outcome the event lane has always had.
    /// </summary>
    public class LiveFixedStringStateTests
    {
        [SetUp]
        public void ResetCounts() => LiveFixedStringStats.Reset();

        [TearDown]
        public void ReleaseCounts() => LiveFixedStringStats.Reset();

        [Test]
        public void TheBlock_HoldsTextAsAFixedWidth()
        {
            var field = typeof(FixedTextProbe.LiveStateBlock).GetField("_title");

            Assert.IsNotNull(field, "the declared text member did not reach the block");
            Assert.AreEqual(typeof(LiveFixedString32), field.FieldType);
        }

        [Test]
        public void AWidthCostsItsBytesPlusItsLength()
        {
            // What a member on this lane costs every frame, which is the number the declaration is
            // choosing between. The length is two bytes because two of its values are markers.
            Assert.AreEqual(32 + 2, UnsafeUtility.SizeOf<LiveFixedString32>());
            Assert.AreEqual(64 + 2, UnsafeUtility.SizeOf<LiveFixedString64>());
            Assert.AreEqual(128 + 2, UnsafeUtility.SizeOf<LiveFixedString128>());
            Assert.AreEqual(256 + 2, UnsafeUtility.SizeOf<LiveFixedString256>());
        }

        [Test]
        public void TheBlockIsStillUnmanaged_SoAFrameCanCarryItVerbatim()
        {
            Assert.DoesNotThrow(() => _RequireUnmanaged<FixedTextProbe.LiveStateBlock>());
        }

        private static void _RequireUnmanaged<T>() where T : unmanaged { }

        [Test]
        public void CaptureThenApply_CarriesTheTextAcross()
        {
            var captured = new FixedTextProbe { title = "front camera", weight = 0.5f };
            var restored = new FixedTextProbe();
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            Assert.IsTrue(bridge.Apply(restored, ownerId: 1, state));

            Assert.AreEqual("front camera", restored.title);
            Assert.AreEqual(0.5f, restored.weight);
        }

        [Test]
        public void AWidthCountsUtf8Bytes_NotCharacters()
        {
            // Ten kanji are thirty bytes and fit; eleven are thirty-three and do not. The width is
            // a claim about bytes, and a declaration that counted characters would be wrong by
            // three times over exactly the text this product is written for.
            var fits = new string('あ', 10);
            var probe = new FixedTextProbe { title = fits };
            var restored = new FixedTextProbe();
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(probe, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(fits, restored.title);
            Assert.AreEqual(0, LiveFixedStringStats.unrepresentableCount);
        }

        [Test]
        public void TextTooLongForItsWidth_IsNotCarried_AndLeavesTheTargetAlone()
        {
            var probe = new FixedTextProbe { title = new string('あ', 11) };
            var restored = new FixedTextProbe { title = "untouched" };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(probe, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);

            // Not shortened and not blanked: a value nobody set would be written back on replay and
            // then agree with itself under comparison, which is worse than a value that is missing.
            Assert.AreEqual("untouched", restored.title);
            Assert.AreEqual(1, LiveFixedStringStats.unrepresentableCount);
        }

        [Test]
        public void ANullStringIsNotAnEmptyOne()
        {
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(new FixedTextProbe { title = null }, ownerId: 1, state, default, time: 0);

            var restored = new FixedTextProbe { title = "something" };
            bridge.Apply(restored, ownerId: 1, state);
            Assert.IsNull(restored.title);

            bridge.Capture(new FixedTextProbe { title = string.Empty }, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);
            Assert.AreEqual(string.Empty, restored.title);
        }

        [Test]
        public void ApplyingTextThatHasNotChanged_DoesNotRunTheSetter()
        {
            // The state lane writes every member every frame. Without this, a replay runs the
            // setter sixty times a second for a value that has not moved -- and the setter behind
            // an asset reference answers that by loading.
            var captured = new FixedTextShadowProbe { selection = "avatar-a" };
            var restored = new FixedTextShadowProbe { selection = "avatar-a" };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextShadowProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            restored.setterCallCount = 0;
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(0, restored.setterCallCount);
            Assert.AreEqual("avatar-a", restored.selection);
        }

        [Test]
        public void ApplyingTextThatChanged_RunsTheSetterOnce()
        {
            var captured = new FixedTextShadowProbe { selection = "avatar-b" };
            var restored = new FixedTextShadowProbe { selection = "avatar-a" };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextShadowProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            restored.setterCallCount = 0;
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(1, restored.setterCallCount, "the second apply had nothing left to change");
            Assert.AreEqual("avatar-b", restored.selection);
        }

        [Test]
        public void ApplyingAnOrdinaryValueThatHasNotChanged_DoesNotRunItsSetter()
        {
            // Not text, so the guard is the generated byte comparison rather than the fixed
            // string's own. A setter is entitled to do anything; the state lane says the value
            // every frame whether or not it moved.
            var captured = new FixedTextShadowProbe { weight = 2f };
            var restored = new FixedTextShadowProbe { weight = 2f };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextShadowProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            restored.weightSetterCallCount = 0;
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(0, restored.weightSetterCallCount);
            Assert.AreEqual(2f, restored.weight);
        }

        [Test]
        public void ApplyingAnOrdinaryValueThatMoved_RunsItsSetterOnce()
        {
            var captured = new FixedTextShadowProbe { weight = 5f };
            var restored = new FixedTextShadowProbe { weight = 2f };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextShadowProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            restored.weightSetterCallCount = 0;
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(1, restored.weightSetterCallCount, "the second apply had nothing left to change");
            Assert.AreEqual(5f, restored.weight);
        }

        [Test]
        public void APlainFieldIsAssignedOutright()
        {
            // No guard on a field: writing one costs a store either way, so comparing first would
            // only add work. FixedTextProbe._weight is the field case.
            var captured = new FixedTextProbe { weight = 3f };
            var restored = new FixedTextProbe();
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(3f, restored.weight);
        }

        [Test]
        public void AChangedValueRunsItsDeclaredReaction()
        {
            var captured = new ReactiveStateProbe { mode = 2, asset = "front" };
            var restored = new ReactiveStateProbe();
            var bridge = StateBridgeRegistry.Find(typeof(ReactiveStateProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(1, restored.modeReactions);
            Assert.AreEqual(1, restored.assetReactions);

            // The reaction reads the value off the member, which is where a live write would have
            // left it too -- so both paths reach the effect the same way.
            Assert.AreEqual("front", restored.loaded);
        }

        [Test]
        public void AValueThatDidNotMove_RunsNoReaction()
        {
            // The point of a reaction rather than a per-frame poll: the state lane says the value
            // every frame, and reacting every frame would reload the asset sixty times a second.
            var captured = new ReactiveStateProbe { mode = 2, asset = "front" };
            var restored = new ReactiveStateProbe { mode = 2, asset = "front" };
            var bridge = StateBridgeRegistry.Find(typeof(ReactiveStateProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(0, restored.modeReactions);
            Assert.AreEqual(0, restored.assetReactions);
        }

        [Test]
        public void ReapplyingTheSameFrame_ReactsOnlyOnce()
        {
            // Scrubbing lands on the same frame again and again; a reaction that fired each time
            // would reload on every mouse move.
            var captured = new ReactiveStateProbe { mode = 7, asset = "back" };
            var restored = new ReactiveStateProbe();
            var bridge = StateBridgeRegistry.Find(typeof(ReactiveStateProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);

            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(1, restored.modeReactions);
            Assert.AreEqual(1, restored.assetReactions);
        }

        [Test]
        public void AMemberWithNoReaction_IsStillAPlainAssignment()
        {
            var captured = new ReactiveStateProbe { quiet = 4f };
            var restored = new ReactiveStateProbe();
            var bridge = StateBridgeRegistry.Find(typeof(ReactiveStateProbe));

            using var state = new StateBlockSet();
            bridge.Capture(captured, ownerId: 1, state, default, time: 0);
            bridge.Apply(restored, ownerId: 1, state);

            Assert.AreEqual(4f, restored.quiet);
            Assert.AreEqual(0, restored.modeReactions);
        }

        /// <summary>
        /// The viewer shows text as text, not as the length and bytes it is stored in.
        ///
        /// Walked into like any other struct, a member called selectedAvatar reads as "_length: 12"
        /// and a couple of hundred bytes of hex -- the storage rather than the value, under names
        /// nobody wrote.
        /// </summary>
        [Test]
        public void TheViewerReadsTextAsText()
        {
            var probe = new FixedTextProbe { title = "front camera" };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(probe, ownerId: 1, state, default, time: 0);

            var block = state.Find<FixedTextProbe.LiveStateBlock>();
            var bytes = new byte[block.elementSize - block.metaSize];
            block.CopyValueTo(0, bytes);

            var layout = Editor.LiveDataViewer.LiveDataValueLayout.For(
                typeof(FixedTextProbe.LiveStateBlock));

            var row = layout.Find(f => f.label == "_title");
            Assert.IsNotNull(row.label, "the text member did not get a row of its own");
            Assert.IsFalse(layout.Exists(f => f.label == "_length" || f.label == "_utf8"),
                "the viewer walked into the storage instead of reading the value");

            Assert.AreEqual("\"front camera\"",
                Editor.LiveDataViewer.LiveDataValueLayout.Read(bytes, bytes.Length, row));
        }

        [Test]
        public void TheViewerSaysWhenTextWasNotCarried()
        {
            // The two markers are worth seeing as themselves: an empty line would read as "it is
            // empty", which is a different thing from "it was too long to carry".
            var probe = new FixedTextProbe { title = new string('あ', 11) };
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            using var state = new StateBlockSet();
            bridge.Capture(probe, ownerId: 1, state, default, time: 0);

            var block = state.Find<FixedTextProbe.LiveStateBlock>();
            var bytes = new byte[block.elementSize - block.metaSize];
            block.CopyValueTo(0, bytes);

            var layout = Editor.LiveDataViewer.LiveDataValueLayout.For(
                typeof(FixedTextProbe.LiveStateBlock));
            var row = layout.Find(f => f.label == "_title");

            var text = Editor.LiveDataViewer.LiveDataValueLayout.Read(bytes, bytes.Length, row);
            Assert.IsNotEmpty(text);
            Assert.AreNotEqual("\"\"", text, "a value that was not carried must not read as empty");
        }

        [Test]
        public void ABridgeSaysWhichMembersItActuallyCarries()
        {
            // Declaring the state lane and being carried by it are two different things, and only
            // the bridge knows which. LiveStateCarriage asks this to decide whether a write still
            // needs an event record.
            var bridge = StateBridgeRegistry.Find(typeof(FixedTextProbe));

            Assert.IsTrue(bridge.Carries("_title"));
            Assert.IsTrue(bridge.Carries("_weight"));
            Assert.IsFalse(bridge.Carries("somethingElse"));
        }

        [Test]
        public void AShadowedTextMemberTravelsThroughItsProperty()
        {
            // The field declares the lane, the property carries the value. The block names the
            // property, so a getter that reads something else entirely still reports the truth.
            var field = typeof(FixedTextShadowProbe.LiveStateBlock).GetField("selection");

            Assert.IsNotNull(field, "the block named the field instead of the property it stands behind");
            Assert.AreEqual(typeof(LiveFixedString64), field.FieldType);
        }
    }
}
