// Copyright (c) You-Ri, 2026

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lilium.RemoteControl.SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public sealed class ExposedClassGenerator : IIncrementalGenerator
    {
        const string kExposedClassAttributeName = "Lilium.RemoteControl.ExposedClassAttribute";
        const string kExposedPropertyAttributeName = "Lilium.RemoteControl.ExposedPropertyAttribute";
        const string kExposedFieldAttributeName = "Lilium.RemoteControl.ExposedFieldAttribute";
        const string kExposedFunctionAttributeName = "Lilium.RemoteControl.ExposedFunctionAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Roslyn 4.3 で導入された ForAttributeWithMetadataName は使わない
            // (Unity 2022.3 の古いパッチが Roslyn 4.0 系の場合に動作させるため)
            var classes = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0,
                transform: static (ctx, _) => _Transform(ctx))
                .Where(static c => c != null)
                .Collect();

            context.RegisterSourceOutput(classes, static (spc, list) =>
            {
                if (list.IsDefaultOrEmpty) return;
                var source = _Emit(list);
                spc.AddSource("ExposedClassDeclarationOrder.g.cs", source);
            });
        }

        static ClassInfo _Transform(GeneratorSyntaxContext ctx)
        {
            var typeNode = (TypeDeclarationSyntax)ctx.Node;
            if (ctx.SemanticModel.GetDeclaredSymbol(typeNode) is not INamedTypeSymbol typeSymbol) return null;
            if (typeSymbol.IsGenericType) return null;

            // [ExposedClass] が付いていなければスキップ
            if (!_HasAttributeOnSymbol(typeSymbol, kExposedClassAttributeName)) return null;

            var members = ImmutableArray.CreateBuilder<string>();

            foreach (var member in typeNode.Members)
            {
                switch (member)
                {
                    case PropertyDeclarationSyntax prop:
                        if (_HasMemberAttribute(ctx.SemanticModel, prop, kExposedPropertyAttributeName))
                            members.Add(prop.Identifier.ValueText);
                        break;
                    case FieldDeclarationSyntax field:
                        if (_HasMemberAttribute(ctx.SemanticModel, field, kExposedFieldAttributeName))
                        {
                            // フィールドは複数変数宣言可能 (`int a, b;`) なので全部拾う
                            foreach (var v in field.Declaration.Variables)
                                members.Add(v.Identifier.ValueText);
                        }
                        break;
                    case MethodDeclarationSyntax method:
                        if (_HasMemberAttribute(ctx.SemanticModel, method, kExposedFunctionAttributeName))
                            members.Add(method.Identifier.ValueText);
                        break;
                }
            }

            if (members.Count == 0) return null;

            return new ClassInfo(
                typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                members.ToImmutable());
        }

        static bool _HasMemberAttribute(SemanticModel model, MemberDeclarationSyntax member, string fullName)
        {
            foreach (var attrList in member.AttributeLists)
            {
                foreach (var attr in attrList.Attributes)
                {
                    var symbol = model.GetSymbolInfo(attr).Symbol;
                    if (symbol is not IMethodSymbol ctor) continue;
                    if (ctor.ContainingType.ToDisplayString() == fullName) return true;
                }
            }
            return false;
        }

        static bool _HasAttributeOnSymbol(ISymbol symbol, string fullName)
        {
            foreach (var attr in symbol.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == fullName) return true;
            }
            return false;
        }

        static string _Emit(ImmutableArray<ClassInfo> classes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by Lilium.RemoteControl.SourceGenerator");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();
            sb.AppendLine("namespace Lilium.RemoteControl.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"Lilium.RemoteControl.SourceGenerator\", \"1.0\")]");
            sb.AppendLine("    internal static class ExposedClassDeclarationOrder");
            sb.AppendLine("    {");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        internal static void Register()");
            sb.AppendLine("        {");

            foreach (var info in classes)
            {
                if (info == null) continue;
                sb.Append("            global::Lilium.RemoteControl.ExposedClassDeclarationOrderTable.Register(typeof(");
                sb.Append(info.FullyQualifiedName);
                sb.Append("), new string[] {");
                for (int i = 0; i < info.MemberNames.Length; i++)
                {
                    if (i > 0) sb.Append(',');
                    sb.Append(' ');
                    sb.Append('"');
                    sb.Append(info.MemberNames[i]);
                    sb.Append('"');
                }
                sb.AppendLine(" });");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            // ModuleInitializerAttribute polyfill (netstandard2.0 互換)
            sb.AppendLine("#if !NET5_0_OR_GREATER");
            sb.AppendLine("namespace System.Runtime.CompilerServices");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]");
            sb.AppendLine("    internal sealed class ModuleInitializerAttribute : global::System.Attribute { }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");

            return sb.ToString();
        }

        sealed class ClassInfo
        {
            public string FullyQualifiedName { get; }
            public ImmutableArray<string> MemberNames { get; }

            public ClassInfo(string fullyQualifiedName, ImmutableArray<string> memberNames)
            {
                FullyQualifiedName = fullyQualifiedName;
                MemberNames = memberNames;
            }

            public override bool Equals(object obj)
            {
                return obj is ClassInfo other
                    && FullyQualifiedName == other.FullyQualifiedName
                    && MemberNames.SequenceEqual(other.MemberNames);
            }

            public override int GetHashCode()
            {
                var hash = FullyQualifiedName?.GetHashCode() ?? 0;
                foreach (var n in MemberNames) hash = hash * 31 + (n?.GetHashCode() ?? 0);
                return hash;
            }
        }
    }
}
